language: python
python:
  - "2.7"

sudo: enabled

script:
  - make

before_install:
  - npm install -g less request
  - git clone https://github.com/viur-framework/pyjs.git
  - pushd pyjs && sudo python setup.py install && popd
  - git submodule init && git submodule update
 
